Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'lib/chef/knife/vsphere_vm_vnc_set.rb'

Lint/AssignmentInCondition:
  Exclude:
    - 'lib/chef/knife/vsphere_vm_disk_list.rb'

Lint/EmptyWhen:
  Exclude:
    - 'lib/chef/knife/vsphere_vm_network_add.rb'

Lint/ShadowingOuterLocalVariable:
  Exclude:
    - 'lib/chef/knife/vsphere_vm_clone.rb'

Lint/UselessAssignment:
  Exclude:
    - 'lib/chef/knife/vsphere_vm_clone.rb'
    - 'lib/chef/knife/vsphere_vm_disk_extend.rb'
    - 'lib/chef/knife/vsphere_vm_property_set.rb'

Naming/VariableName:
  Exclude:
    - 'lib/chef/knife/helpers/base_vsphere_command.rb'
    - 'lib/chef/knife/vsphere_cluster_list.rb'
    - 'lib/chef/knife/vsphere_vm_delete.rb'
    - 'lib/chef/knife/vsphere_vm_vmdk_add.rb'
